name: 'Maven Jar Publish'
description: 'maven package jar and upload to releases'
author: 'Eric Lam'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  java-version:
    description: 'the java version to build (if not provied, it will use the ${ maven.compiler.target } properties'
    required: false
    default: 'NONE'
  locate:
    description: 'the location of pom.xml (to build)'
    required: false
    default: '.'
  upload-module:
    description: 'the module path that to upload the artifact. (the module name must same as the module path)'
    required: false
    default: '.'
  body:
    description: 'The release content'
    required: false
  body-path:
    description: 'The release content by file (if specificed then body will be ignored)'
    required: false
  draft:
    description: 'whether the release is draft'
    required: false
    default: false
  pre-release:
    description: 'whether the release is pre-release'
    required: false
    default: false

runs:
  using: "composite"
  steps:
    - name: Setup variables
      id: project
      shell: bash
      run: sh ${{ github.action_path }}/setup_variables.sh ${{ inputs.upload-module }} ${{ inputs.java-version }}
      
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ steps.project.outputs.jdk-version }}

    - name: Packaging Jar
      id: packaging-jar
      shell: bash
      run: |
        mvn -B package --file ${{ inputs.locate }}/pom.xml
    - name: Delete existing release and tag
      id: delete-tag-release
      uses: dev-drprasad/delete-tag-and-release@v1.0
      with:
        tag_name: ${{ steps.project.outputs.version }}
        delete_release: true

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ steps.project.outputs.version }}
        release_name: Release ${{ github.repository }} v${{ steps.project.outputs.version }}
        body: ${{ inputs.body }}
        body_path: ${{ inputs.body-path }}
        draft: ${{ inputs.draft }}
        prerelease: ${{ inputs.pre-release }}

    - name: Upload Release jar
      id: upload-release-asset-jar
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ inputs.upload-module }}/target/${{ steps.project.outputs.artifact }}.jar
        asset_name: ${{ steps.project.outputs.artifact }}.jar
        asset_content_type: application/java-archive

