name: Test Packaing Jar And Upload

env:
  locate: '.'

on:
  push:
    branches: [ develop ]

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eric2788/maven-jar-publish@master
      with:
        body: changelog.md
        body-use-file: true


  test_variables:
    if: ${{ false }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test variables
      run: |
        version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f ${{ env.locate }}/pom.xml)
        echo $version
        echo "version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout -f ${{ env.locate }}/pom.xml)"
        echo $version
