name: Test Packaing Jar And Upload

env:
  locate: '.'

on:
  push:
    branches: [ develop ]

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eric2788/maven-jar-publish@develop
      with:
        body: changelog.md
        body-use-file: true


  test_variables:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: test variables
      run: |
        artifact=$(mvn help:evaluate -Dexpression=project.build.finalName -q -DforceStdout -f ${{ inputs.locate }}/pom.xml)
        echo $artifact
