name: Test Packaing Jar And Upload

on:
  push:
    branches: [ master ]

jobs:
  build_jar:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: eric2788/maven-jar-publish@master
      with:
        body: changelog.md
        body-use-file: true
